// <auto-generated />
using System;
using AssistenciaPlus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistenciaPlus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518100000_AddGrupMestre")]
    partial class AddGrupMestre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Alumne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cognom1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("cognom1");

                    b.Property<string>("Cognom2")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("cognom2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataNaixement")
                        .HasColumnType("date")
                        .HasColumnName("data_naixement");

                    b.Property<bool>("EsActiu")
                        .HasColumnType("boolean")
                        .HasColumnName("es_actiu");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text")
                        .HasColumnName("foto_path");

                    b.Property<Guid>("GrupId")
                        .HasColumnType("uuid")
                        .HasColumnName("grup_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nom");

                    b.Property<int>("OrdreFusteta")
                        .HasColumnType("integer")
                        .HasColumnName("ordre_fusteta");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alumnes");

                    b.HasIndex("GrupId")
                        .HasDatabaseName("ix_alumnes_grup_id");

                    b.ToTable("alumnes", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.AnyAcademic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataFi")
                        .HasColumnType("date")
                        .HasColumnName("data_fi");

                    b.Property<DateOnly>("DataInici")
                        .HasColumnType("date")
                        .HasColumnName("data_inici");

                    b.Property<bool>("EsActiu")
                        .HasColumnType("boolean")
                        .HasColumnName("es_actiu");

                    b.Property<DateOnly>("FiT1")
                        .HasColumnType("date")
                        .HasColumnName("fi_t1");

                    b.Property<DateOnly>("FiT2")
                        .HasColumnType("date")
                        .HasColumnName("fi_t2");

                    b.Property<DateOnly>("FiT3")
                        .HasColumnType("date")
                        .HasColumnName("fi_t3");

                    b.Property<DateOnly>("IniciT1")
                        .HasColumnType("date")
                        .HasColumnName("inici_t1");

                    b.Property<DateOnly>("IniciT2")
                        .HasColumnType("date")
                        .HasColumnName("inici_t2");

                    b.Property<DateOnly>("IniciT3")
                        .HasColumnType("date")
                        .HasColumnName("inici_t3");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nom");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_anys_academics");

                    b.HasIndex("EsActiu")
                        .HasDatabaseName("ix_anys_academics_es_actiu");

                    b.ToTable("anys_academics", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.AssistenciaAlumne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlumneId")
                        .HasColumnType("uuid")
                        .HasColumnName("alumne_id");

                    b.Property<bool>("AplicatRestaDia")
                        .HasColumnType("boolean")
                        .HasColumnName("aplicat_resta_dia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Estat")
                        .HasColumnType("integer")
                        .HasColumnName("estat");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("MinutsRetard")
                        .HasColumnType("integer")
                        .HasColumnName("minuts_retard");

                    b.Property<int?>("Motiu")
                        .HasColumnType("integer")
                        .HasColumnName("motiu");

                    b.Property<string>("Observacio")
                        .HasColumnType("text")
                        .HasColumnName("observacio");

                    b.Property<Guid>("RegistreAssistenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("registre_assistencia_id");

                    b.Property<bool?>("Torna")
                        .HasColumnType("boolean")
                        .HasColumnName("torna");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assistencies_alumnes");

                    b.HasIndex("AlumneId")
                        .HasDatabaseName("ix_assistencies_alumnes_alumne_id");

                    b.HasIndex("RegistreAssistenciaId", "AlumneId")
                        .IsUnique()
                        .HasDatabaseName("ix_assistencies_alumnes_registre_assistencia_id_alumne_id");

                    b.ToTable("assistencies_alumnes", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Cicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cicles");

                    b.ToTable("cicles", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Curs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cicle_id");

                    b.Property<string>("Codi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UsaModeFusteta")
                        .HasColumnType("boolean")
                        .HasColumnName("usa_mode_fusteta");

                    b.HasKey("Id")
                        .HasName("pk_cursos");

                    b.HasIndex("CicleId")
                        .HasDatabaseName("ix_cursos_cicle_id");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.DiaCalendari", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnyAcademicId")
                        .HasColumnType("uuid")
                        .HasColumnName("any_academic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descripcio")
                        .HasColumnType("text")
                        .HasColumnName("descripcio");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("TipusDia")
                        .HasColumnType("integer")
                        .HasColumnName("tipus_dia");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dies_calendari");

                    b.HasIndex("AnyAcademicId", "Data")
                        .IsUnique()
                        .HasDatabaseName("ix_dies_calendari_any_academic_id_data");

                    b.ToTable("dies_calendari", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.FranjaHoraria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EsJornadaIntensiva")
                        .HasColumnType("boolean")
                        .HasColumnName("es_jornada_intensiva");

                    b.Property<bool>("EsMati")
                        .HasColumnType("boolean")
                        .HasColumnName("es_mati");

                    b.Property<TimeOnly>("HoraFi")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fi");

                    b.Property<TimeOnly>("HoraInici")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inici");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nom");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_franjes_horaries");

                    b.ToTable("franjes_horaries", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Grup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnyAcademicId")
                        .HasColumnType("uuid")
                        .HasColumnName("any_academic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CursId")
                        .HasColumnType("uuid")
                        .HasColumnName("curs_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Lletra")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("lletra");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grups");

                    b.HasIndex("AnyAcademicId")
                        .HasDatabaseName("ix_grups_any_academic_id");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_grups_tutor_id");

                    b.HasIndex("CursId", "AnyAcademicId", "Lletra")
                        .IsUnique()
                        .HasDatabaseName("ix_grups_curs_id_any_academic_id_lletra");

                    b.ToTable("grups", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.GrupMestre", b =>
                {
                    b.Property<Guid>("GrupId")
                        .HasColumnType("uuid")
                        .HasColumnName("grup_id");

                    b.Property<Guid>("UsuariId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuari_id");

                    b.Property<DateTime>("AfegitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("afegit_at");

                    b.HasKey("GrupId", "UsuariId")
                        .HasName("pk_grups_mestres");

                    b.HasIndex("UsuariId")
                        .HasDatabaseName("ix_grups_mestres_usuari_id");

                    b.ToTable("grups_mestres", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.RegistreAssistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTime>("DegatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("degat_at");

                    b.Property<Guid>("FranjaHorariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("franja_horaria_id");

                    b.Property<Guid>("GrupId")
                        .HasColumnType("uuid")
                        .HasColumnName("grup_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MestreId")
                        .HasColumnType("uuid")
                        .HasColumnName("mestre_id");

                    b.Property<string>("Observacio")
                        .HasColumnType("text")
                        .HasColumnName("observacio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_registres_assistencia");

                    b.HasIndex("FranjaHorariaId")
                        .HasDatabaseName("ix_registres_assistencia_franja_horaria_id");

                    b.HasIndex("MestreId")
                        .HasDatabaseName("ix_registres_assistencia_mestre_id");

                    b.HasIndex("GrupId", "Data")
                        .HasDatabaseName("ix_registres_assistencia_grup_id_data");

                    b.HasIndex("GrupId", "FranjaHorariaId", "Data")
                        .IsUnique()
                        .HasDatabaseName("ix_registres_assistencia_grup_id_franja_horaria_id_data");

                    b.ToTable("registres_assistencia", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Usuari", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cognom1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("cognom1");

                    b.Property<string>("Cognom2")
                        .HasColumnType("text")
                        .HasColumnName("cognom2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<bool>("EsActiu")
                        .HasColumnType("boolean")
                        .HasColumnName("es_actiu");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text")
                        .HasColumnName("foto_path");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("ca")
                        .HasColumnName("idioma");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimAcces")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultim_acces");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuaris");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuaris_email");

                    b.ToTable("usuaris", (string)null);
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Alumne", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.Grup", "Grup")
                        .WithMany("Alumnes")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alumnes_grups_grup_id");

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.AssistenciaAlumne", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.Alumne", "Alumne")
                        .WithMany("Assistencies")
                        .HasForeignKey("AlumneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assistencies_alumnes_alumnes_alumne_id");

                    b.HasOne("AssistenciaPlus.Domain.Entities.RegistreAssistencia", "RegistreAssistencia")
                        .WithMany("Assistencies")
                        .HasForeignKey("RegistreAssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assistencies_alumnes_registres_assistencia_registre_assiste");

                    b.Navigation("Alumne");

                    b.Navigation("RegistreAssistencia");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Curs", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.Cicle", "Cicle")
                        .WithMany("Cursos")
                        .HasForeignKey("CicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_cicles_cicle_id");

                    b.Navigation("Cicle");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.DiaCalendari", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.AnyAcademic", "AnyAcademic")
                        .WithMany("DiesCalendari")
                        .HasForeignKey("AnyAcademicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dies_calendari_anys_academics_any_academic_id");

                    b.Navigation("AnyAcademic");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Grup", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.AnyAcademic", "AnyAcademic")
                        .WithMany("Grups")
                        .HasForeignKey("AnyAcademicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grups_anys_academics_any_academic_id");

                    b.HasOne("AssistenciaPlus.Domain.Entities.Curs", "Curs")
                        .WithMany("Grups")
                        .HasForeignKey("CursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grups_cursos_curs_id");

                    b.HasOne("AssistenciaPlus.Domain.Entities.Usuari", "Tutor")
                        .WithMany("GrupsTutoritzats")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_grups_usuaris_tutor_id");

                    b.Navigation("AnyAcademic");

                    b.Navigation("Curs");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.GrupMestre", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.Grup", "Grup")
                        .WithMany("MestresAutoritzats")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grups_mestres_grups_grup_id");

                    b.HasOne("AssistenciaPlus.Domain.Entities.Usuari", "Usuari")
                        .WithMany("GrupsAutoritzats")
                        .HasForeignKey("UsuariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grups_mestres_usuaris_usuari_id");

                    b.Navigation("Grup");

                    b.Navigation("Usuari");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.RegistreAssistencia", b =>
                {
                    b.HasOne("AssistenciaPlus.Domain.Entities.FranjaHoraria", "FranjaHoraria")
                        .WithMany("RegistresAssistencia")
                        .HasForeignKey("FranjaHorariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registres_assistencia_franjes_horaries_franja_horaria_id");

                    b.HasOne("AssistenciaPlus.Domain.Entities.Grup", "Grup")
                        .WithMany("RegistresAssistencia")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registres_assistencia_grups_grup_id");

                    b.HasOne("AssistenciaPlus.Domain.Entities.Usuari", "Mestre")
                        .WithMany("RegistresPassats")
                        .HasForeignKey("MestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registres_assistencia_usuaris_mestre_id");

                    b.Navigation("FranjaHoraria");

                    b.Navigation("Grup");

                    b.Navigation("Mestre");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Alumne", b =>
                {
                    b.Navigation("Assistencies");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.AnyAcademic", b =>
                {
                    b.Navigation("DiesCalendari");

                    b.Navigation("Grups");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Cicle", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Curs", b =>
                {
                    b.Navigation("Grups");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.FranjaHoraria", b =>
                {
                    b.Navigation("RegistresAssistencia");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Grup", b =>
                {
                    b.Navigation("Alumnes");

                    b.Navigation("MestresAutoritzats");

                    b.Navigation("RegistresAssistencia");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.RegistreAssistencia", b =>
                {
                    b.Navigation("Assistencies");
                });

            modelBuilder.Entity("AssistenciaPlus.Domain.Entities.Usuari", b =>
                {
                    b.Navigation("GrupsAutoritzats");

                    b.Navigation("GrupsTutoritzats");

                    b.Navigation("RegistresPassats");
                });
#pragma warning restore 612, 618
        }
    }
}
